# Generated by Django 3.2 on 2021-04-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_blog', models.TextField()),
                ('data_blog', models.TextField()),
                ('name_blogers', models.TextField()),
            ],
        ),
    ]
