# Generated by Django 3.2 on 2021-05-31 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=225, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_blog', models.TextField(verbose_name='Название')),
                ('slug', models.SlugField(max_length=225, unique=True, verbose_name='URL')),
                ('data_blog', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('data_blog_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('description_blog', models.TextField(null=True, verbose_name='Описание')),
                ('name_blogers', models.TextField(verbose_name='Имя блогера')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home_messages.category')),
            ],
        ),
    ]
