# Generated by Django 3.2 on 2021-04-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_blog',
            field=models.TextField(null=True),
        ),
    ]
