# Generated by Django 3.1.7 on 2021-04-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_messages', '0002_blog_description_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='data_blog',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description_blog',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name_blog',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name_blogers',
            field=models.TextField(verbose_name='Имя блогера'),
        ),
    ]
