# Generated by Django 3.1.7 on 2021-05-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_messages', '0006_auto_20210507_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='data_blog_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='data_blog',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
